language: rust
os: linux

cache:
  - cargo

rust:
  - stable

script:
  - mdbook build blog && mdbook test blog
  
deploy:
  provider: pages
  strategy: git
  edge: true
  cleanup: false
  github-token: $GITHUB_TOKEN
  local-dir: blog/book
  keep-history: false
  on:
    branch: main
  target_branch: gh-pages
